{{- if .Values.certmanager.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gatewayapi-operator-validating-webhook-configuration
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/serving-cert
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: gatewayapi-operator-webhook-service
        namespace: {{ .Values.namespace }}
        path: /gatewayapi-operator-httproute-validator
    failurePolicy: Ignore
    name: vhttproute-v1.kb.io
    rules:
      - apiGroups:
          - gateway.networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - httproutes
    sideEffects: None
{{- end }}
